//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RosinkaApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildGroup
    {
        public int ChildGroupId { get; set; }
        public Nullable<int> ChildId { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        public virtual Child Child { get; set; }
        public virtual Group Group { get; set; }
    }
}
