//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RosinkaApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group()
        {
            this.ChildGroup = new HashSet<ChildGroup>();
            this.GroupMentor = new HashSet<GroupMentor>();
        }
    
        public int GoupID { get; set; }
        public string GroupName { get; set; }
        public string GroupStatus { get; set; }
        public Nullable<int> NumberOfRoom { get; set; }
        public Nullable<int> GroupTypeId { get; set; }
    
        public virtual ICollection<ChildGroup> ChildGroup { get; set; }
        public virtual GroupType GroupType { get; set; }
        public virtual Room Room { get; set; }
        public virtual ICollection<GroupMentor> GroupMentor { get; set; }
    }
}
