//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RosinkaApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HealthCard()
        {
            this.Child = new HashSet<Child>();
        }
    
        public int HealthCardId { get; set; }
        public string Disability { get; set; }
        public string HealthGroup { get; set; }
        public string ExtensiveTreatment { get; set; }
        public byte[] VaccinationCertificateFirstPage { get; set; }
        public string Comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Child> Child { get; set; }
    }
}
