//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RosinkaApp.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RosinkaDbEntities : DbContext
    {
        public RosinkaDbEntities()
            : base("name=RosinkaDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BirthCertificate> BirthCertificate { get; set; }
        public virtual DbSet<Child> Child { get; set; }
        public virtual DbSet<ChildGroup> ChildGroup { get; set; }
        public virtual DbSet<ChildParent> ChildParent { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<GroupMentor> GroupMentor { get; set; }
        public virtual DbSet<GroupType> GroupType { get; set; }
        public virtual DbSet<HealthCard> HealthCard { get; set; }
        public virtual DbSet<Parent> Parent { get; set; }
        public virtual DbSet<Passport> Passport { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
